---
title: "Literature Review"
format: html
editor: 
  markdown: 
    wrap: sentence
bibliography: references.bib
---

# Outline

-   Motivation
-   Overview of graphs
-   Perception of graphs
    -   What makes a good graph
    -   Chart junk
    -   Decision times?
    -   Cleveland and McGill
-   2d vs. 3d
    -   Advances in computer graphics
    -   Bar graphs
    -   Heat maps

# Motivation

# Overview of graphs

-   Design + purpose

-   Gestalt principles?

Data visualizations offer a quick method to summarize any amount of information.
The visual summary offers improved decision times [@brewer2012], pattern recognition, and increased recollection (source).
(Expand on sources, I know I've seen these papers, Dickson et al (1986) is mentioned in Barfield, check this out).
Clearly, data visualizations have proven beneficial over the years and merit further expansion.

Perhaps the greatest advantage of data visualizations is to help see what information is contained within data.
For example, Anscombe's Quartet (source) contains four bivariate data sets that all have, within small rounding errors, identical descriptive statistics (figure).
While the trends of the data sets are apparent when graphed, they would be missed using the descriptive statistics and possibly when viewed in a tabular format.

In the case of multivariate data, heat maps are a common method to show trends in a row-column format, utilizing color shading to display values [@wilkinson2009].

# Perception of graphs

-   Cleveland and McGill
-   Heer and Bostock
-   VanderPlas (FOCUS ON THIS ONE AND ITS REFERENCES)

[Pre-attentive features]{.underline}

A good data visualization uses many design facets to promote fast interpretations and pattern recognition.
The most immediate of these facets are called preattentive features, which are components that are identifiable in 500ms or less (cite?).
These include, but are not limited to, the features of length, size, color, 3D depth cues, and lighting direction (See Healey Fig 3 for features and references).
(Summarize one-two studies on preattentive features, Healey and Enns are good choices).
Furthermore, even the orientation of a graph can influence the amount of time when making "A \> B" comparisons [@fischer2005], where vertical bar graphs had faster decision times than horizontal bar graphs (I don't like this phrasing, polish out).
With many options for constructing visual stimuli, it is evident that design choices matter.

[EPTs and accuracy]{.underline}

Another key aspect in creating a good data visualization is leveraging appropriate graph types through the use of comparison stimuli called Elementary Perceptual Tasks (EPTs).
These EPTs were first introduced by @cleveland1984 as a theoretical framework for ranking methods of graphical representations of data when tasked with numerically estimating the difference of two values; these graphical representations include, but not limited to, the following EPTs: positional along a common scale, length, and angle.
What @cleveland1984 found is that the type of graph can influence the accuracy in numerical comparisons.
The findings by Cleveland and McGill were replicated by @heer2010 using Amazon Mechanical Turk, demonstrating the importance of graph type across different populations.
(Additional papers on EPTs)

[Chart-junk + other factors]{.underline}

Even when a data visualization makes use of optimal data features, other factors, such as grid lines and artistic clutter, can negatively affect the readability of graphs.
(tufte)

[Importance of Graph Designs (summary of everything above)??]{.underline}

In summary, the design of

# 2D and 3D graphs

```{=html}
<!---
This paragraph stems from general Google/Wikipedia research and my current impressions. Will need to find sources to cite!
--->
```
Following the invention of the digital computer in the 1960s, advances in computer graphics allowed for greater control and accessibility for creating data visualizations.
While many graphs first stem from artistic choices, the effectiveness of these graphs may not necessarily be tested before gaining widespread accessibility.
For example, Excel 3 introduced its 3D bar chart feature in 1990, but studies around this time tend to suggest that the 2D bar chart ...
<!-- Briefly mention Barfield / Fischer? -->

A reasonable place to start comparing 2D and 3D graphs is with the bar chart.
This simple graph style helped @cleveland1984 in establishing the ordering of EPTs and can be easily extended into a 3D bar chart for direct comparisons.
While @cleveland1984 evaluated the EPTs of position along a common scale, length, and angle, they theorized that the accuracy of area would be higher than the accuracy of volume.
Depending on the context of information retrieval from a graph, especially with A \> B comparisons, the construction of 2D and 3D bar charts are simply special cases of area and volume comparisons; 2D and 3D bar charts have varying heights based on a data value, along with fixed widths and, in the case of 3D graphs, fixed depths.
This would suggest that the use of 2D graphs should, in theory, be better than 3D graphs.

The theory theory that the EPT of area ranks higher than volume has been evaluated in several studies on 2D and 3D bar charts.
@barfield1989 showed that accuracy between 2D and 3D charts depended on managerial experience level, with less experienced managers having higher accuracy for 2D graphs.
@zacks evaluated the effect of 3D depth cues and found that accuracy decreased for 3D graphs, but the difference in accuracy between 2D and 3D graphs was less when a delay in responses was introduced.
@hughes looked at just noticeable differences in 2D and 3D bar charts, which showed that the noticeable difference was larger for 3D graphs.
Taken together, it is reasonable to suggest that 2D graphs have advantages over 3D graphs.
<!-- Barfield / Fischer / Zacks / Hughes -->

In the case of bar graphs, studies have shown that there may not be a preference to use 3D bar charts.
<!--Barfield / Fischer -->

Extending beyond the the bar graph, it makes sense to effectively use the third dimension for conveying information.
@grinstein2001 discusses several methods to convey higher dimensional data, including 3D scatter plots and height maps.

<!-- Grinstein / Haarman-->

The construction of 3D graphs perhaps requires even more scrutiny, especially when considering rendering options and interactivity.
<!-- Tarr / Norman? / Rodger / Wang-->

Paragraph about current use of true 3D visualizations?

Notes from Susan

-   Include figures

-   "Ans-a-dome"

-   No motivation or multivariate data

-   Connect and synthesize

    -   Post it notes with paper summarizes

-   Goal: this is the blank spot; make the story of the discipline

    -   Visualization and what we know about it, make a story of it

-   Obsidian is a possible way (possible graphics group presentation) (check the subreddit)

-   Zotero integration with Obsidian

Break down the walls

-   Experiment will continue through the summer

    -   Ask Amanda about adding questions to evaluations

    -   Send email about missing kits

Sci-hub plug-in is a good resource

<https://libraries.unl.edu/library-account-logins>

Schedule meeting for week of June 17th; weekly slack updates

\- Triesman: feature integration theory - 10.1016/S0734-189X(85)80004-9, 10.1016/0010-0285(80)90005-5

\- Healey: 10.1145/230562.230563

Check with Amanda for Ta's, keep working on lit review / Susan, office hour schedule for students having access to experiment

10ish hours a week
